-- 0010: OLTP tables for the applications domain. Mutable current state;
-- every change appends to application_events (see 0009) for audit.
--
-- application_id is xid-generated by the service (TEXT, fixed 20 chars).
-- (candidate_id, opportunity_id) is UNIQUE — one application per pair.

CREATE TABLE IF NOT EXISTS applications (
    application_id   TEXT        PRIMARY KEY,
    candidate_id     TEXT        NOT NULL,
    opportunity_id   TEXT        NOT NULL,
    match_id         TEXT        NOT NULL,
    status           TEXT        NOT NULL,                -- see state.go
    current_stage    TEXT,
    metadata         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    submitted_at     TIMESTAMPTZ,
    last_event_id    TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (candidate_id, opportunity_id)
);
CREATE INDEX IF NOT EXISTS applications_candidate_status_idx
    ON applications (candidate_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS application_notes (
    note_id          TEXT        PRIMARY KEY,
    application_id   TEXT        NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    body             TEXT        NOT NULL,
    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS application_notes_app_idx
    ON application_notes (application_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS application_attachments (
    attachment_id    TEXT        PRIMARY KEY,
    application_id   TEXT        NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    r2_key           TEXT        NOT NULL,
    content_type     TEXT        NOT NULL,
    bytes            BIGINT      NOT NULL,
    filename         TEXT,
    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS application_attachments_app_idx
    ON application_attachments (application_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS application_reminders (
    reminder_id      TEXT        PRIMARY KEY,
    application_id   TEXT        NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    due_at           TIMESTAMPTZ NOT NULL,
    status           TEXT        NOT NULL,                -- pending|done|cancelled
    note             TEXT,
    completed_at     TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS application_reminders_due_idx
    ON application_reminders (due_at)
    WHERE status = 'pending' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS application_reminders_app_idx
    ON application_reminders (application_id, due_at)
    WHERE deleted_at IS NULL;
