// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: redirect/v1/redirect.proto

package redirectv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "stawi.jobs/pkg/services/redirectpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RedirectServiceName is the fully-qualified name of the RedirectService service.
	RedirectServiceName = "redirect.v1.RedirectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RedirectServiceCreateLinkProcedure is the fully-qualified name of the RedirectService's
	// CreateLink RPC.
	RedirectServiceCreateLinkProcedure = "/redirect.v1.RedirectService/CreateLink"
	// RedirectServiceGetLinkProcedure is the fully-qualified name of the RedirectService's GetLink RPC.
	RedirectServiceGetLinkProcedure = "/redirect.v1.RedirectService/GetLink"
	// RedirectServiceUpdateLinkProcedure is the fully-qualified name of the RedirectService's
	// UpdateLink RPC.
	RedirectServiceUpdateLinkProcedure = "/redirect.v1.RedirectService/UpdateLink"
	// RedirectServiceDeleteLinkProcedure is the fully-qualified name of the RedirectService's
	// DeleteLink RPC.
	RedirectServiceDeleteLinkProcedure = "/redirect.v1.RedirectService/DeleteLink"
	// RedirectServiceListLinksProcedure is the fully-qualified name of the RedirectService's ListLinks
	// RPC.
	RedirectServiceListLinksProcedure = "/redirect.v1.RedirectService/ListLinks"
	// RedirectServiceGetLinkStatsProcedure is the fully-qualified name of the RedirectService's
	// GetLinkStats RPC.
	RedirectServiceGetLinkStatsProcedure = "/redirect.v1.RedirectService/GetLinkStats"
	// RedirectServiceListClicksProcedure is the fully-qualified name of the RedirectService's
	// ListClicks RPC.
	RedirectServiceListClicksProcedure = "/redirect.v1.RedirectService/ListClicks"
)

// RedirectServiceClient is a client for the redirect.v1.RedirectService service.
type RedirectServiceClient interface {
	// CreateLink creates a new redirect link.
	CreateLink(context.Context, *connect.Request[v1.CreateLinkRequest]) (*connect.Response[v1.CreateLinkResponse], error)
	// GetLink retrieves link details by ID.
	GetLink(context.Context, *connect.Request[v1.GetLinkRequest]) (*connect.Response[v1.GetLinkResponse], error)
	// UpdateLink modifies an existing link.
	UpdateLink(context.Context, *connect.Request[v1.UpdateLinkRequest]) (*connect.Response[v1.UpdateLinkResponse], error)
	// DeleteLink removes a link.
	DeleteLink(context.Context, *connect.Request[v1.DeleteLinkRequest]) (*connect.Response[v1.DeleteLinkResponse], error)
	// ListLinks searches and lists links with filters.
	ListLinks(context.Context, *connect.Request[v1.ListLinksRequest]) (*connect.ServerStreamForClient[v1.ListLinksResponse], error)
	// GetLinkStats returns aggregate click statistics for a link.
	GetLinkStats(context.Context, *connect.Request[v1.GetLinkStatsRequest]) (*connect.Response[v1.GetLinkStatsResponse], error)
	// ListClicks returns detailed click events for a link.
	ListClicks(context.Context, *connect.Request[v1.ListClicksRequest]) (*connect.ServerStreamForClient[v1.ListClicksResponse], error)
}

// NewRedirectServiceClient constructs a client for the redirect.v1.RedirectService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRedirectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RedirectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	redirectServiceMethods := v1.File_redirect_v1_redirect_proto.Services().ByName("RedirectService").Methods()
	return &redirectServiceClient{
		createLink: connect.NewClient[v1.CreateLinkRequest, v1.CreateLinkResponse](
			httpClient,
			baseURL+RedirectServiceCreateLinkProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("CreateLink")),
			connect.WithClientOptions(opts...),
		),
		getLink: connect.NewClient[v1.GetLinkRequest, v1.GetLinkResponse](
			httpClient,
			baseURL+RedirectServiceGetLinkProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("GetLink")),
			connect.WithClientOptions(opts...),
		),
		updateLink: connect.NewClient[v1.UpdateLinkRequest, v1.UpdateLinkResponse](
			httpClient,
			baseURL+RedirectServiceUpdateLinkProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("UpdateLink")),
			connect.WithClientOptions(opts...),
		),
		deleteLink: connect.NewClient[v1.DeleteLinkRequest, v1.DeleteLinkResponse](
			httpClient,
			baseURL+RedirectServiceDeleteLinkProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("DeleteLink")),
			connect.WithClientOptions(opts...),
		),
		listLinks: connect.NewClient[v1.ListLinksRequest, v1.ListLinksResponse](
			httpClient,
			baseURL+RedirectServiceListLinksProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("ListLinks")),
			connect.WithClientOptions(opts...),
		),
		getLinkStats: connect.NewClient[v1.GetLinkStatsRequest, v1.GetLinkStatsResponse](
			httpClient,
			baseURL+RedirectServiceGetLinkStatsProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("GetLinkStats")),
			connect.WithClientOptions(opts...),
		),
		listClicks: connect.NewClient[v1.ListClicksRequest, v1.ListClicksResponse](
			httpClient,
			baseURL+RedirectServiceListClicksProcedure,
			connect.WithSchema(redirectServiceMethods.ByName("ListClicks")),
			connect.WithClientOptions(opts...),
		),
	}
}

// redirectServiceClient implements RedirectServiceClient.
type redirectServiceClient struct {
	createLink   *connect.Client[v1.CreateLinkRequest, v1.CreateLinkResponse]
	getLink      *connect.Client[v1.GetLinkRequest, v1.GetLinkResponse]
	updateLink   *connect.Client[v1.UpdateLinkRequest, v1.UpdateLinkResponse]
	deleteLink   *connect.Client[v1.DeleteLinkRequest, v1.DeleteLinkResponse]
	listLinks    *connect.Client[v1.ListLinksRequest, v1.ListLinksResponse]
	getLinkStats *connect.Client[v1.GetLinkStatsRequest, v1.GetLinkStatsResponse]
	listClicks   *connect.Client[v1.ListClicksRequest, v1.ListClicksResponse]
}

// CreateLink calls redirect.v1.RedirectService.CreateLink.
func (c *redirectServiceClient) CreateLink(ctx context.Context, req *connect.Request[v1.CreateLinkRequest]) (*connect.Response[v1.CreateLinkResponse], error) {
	return c.createLink.CallUnary(ctx, req)
}

// GetLink calls redirect.v1.RedirectService.GetLink.
func (c *redirectServiceClient) GetLink(ctx context.Context, req *connect.Request[v1.GetLinkRequest]) (*connect.Response[v1.GetLinkResponse], error) {
	return c.getLink.CallUnary(ctx, req)
}

// UpdateLink calls redirect.v1.RedirectService.UpdateLink.
func (c *redirectServiceClient) UpdateLink(ctx context.Context, req *connect.Request[v1.UpdateLinkRequest]) (*connect.Response[v1.UpdateLinkResponse], error) {
	return c.updateLink.CallUnary(ctx, req)
}

// DeleteLink calls redirect.v1.RedirectService.DeleteLink.
func (c *redirectServiceClient) DeleteLink(ctx context.Context, req *connect.Request[v1.DeleteLinkRequest]) (*connect.Response[v1.DeleteLinkResponse], error) {
	return c.deleteLink.CallUnary(ctx, req)
}

// ListLinks calls redirect.v1.RedirectService.ListLinks.
func (c *redirectServiceClient) ListLinks(ctx context.Context, req *connect.Request[v1.ListLinksRequest]) (*connect.ServerStreamForClient[v1.ListLinksResponse], error) {
	return c.listLinks.CallServerStream(ctx, req)
}

// GetLinkStats calls redirect.v1.RedirectService.GetLinkStats.
func (c *redirectServiceClient) GetLinkStats(ctx context.Context, req *connect.Request[v1.GetLinkStatsRequest]) (*connect.Response[v1.GetLinkStatsResponse], error) {
	return c.getLinkStats.CallUnary(ctx, req)
}

// ListClicks calls redirect.v1.RedirectService.ListClicks.
func (c *redirectServiceClient) ListClicks(ctx context.Context, req *connect.Request[v1.ListClicksRequest]) (*connect.ServerStreamForClient[v1.ListClicksResponse], error) {
	return c.listClicks.CallServerStream(ctx, req)
}

// RedirectServiceHandler is an implementation of the redirect.v1.RedirectService service.
type RedirectServiceHandler interface {
	// CreateLink creates a new redirect link.
	CreateLink(context.Context, *connect.Request[v1.CreateLinkRequest]) (*connect.Response[v1.CreateLinkResponse], error)
	// GetLink retrieves link details by ID.
	GetLink(context.Context, *connect.Request[v1.GetLinkRequest]) (*connect.Response[v1.GetLinkResponse], error)
	// UpdateLink modifies an existing link.
	UpdateLink(context.Context, *connect.Request[v1.UpdateLinkRequest]) (*connect.Response[v1.UpdateLinkResponse], error)
	// DeleteLink removes a link.
	DeleteLink(context.Context, *connect.Request[v1.DeleteLinkRequest]) (*connect.Response[v1.DeleteLinkResponse], error)
	// ListLinks searches and lists links with filters.
	ListLinks(context.Context, *connect.Request[v1.ListLinksRequest], *connect.ServerStream[v1.ListLinksResponse]) error
	// GetLinkStats returns aggregate click statistics for a link.
	GetLinkStats(context.Context, *connect.Request[v1.GetLinkStatsRequest]) (*connect.Response[v1.GetLinkStatsResponse], error)
	// ListClicks returns detailed click events for a link.
	ListClicks(context.Context, *connect.Request[v1.ListClicksRequest], *connect.ServerStream[v1.ListClicksResponse]) error
}

// NewRedirectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRedirectServiceHandler(svc RedirectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	redirectServiceMethods := v1.File_redirect_v1_redirect_proto.Services().ByName("RedirectService").Methods()
	redirectServiceCreateLinkHandler := connect.NewUnaryHandler(
		RedirectServiceCreateLinkProcedure,
		svc.CreateLink,
		connect.WithSchema(redirectServiceMethods.ByName("CreateLink")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceGetLinkHandler := connect.NewUnaryHandler(
		RedirectServiceGetLinkProcedure,
		svc.GetLink,
		connect.WithSchema(redirectServiceMethods.ByName("GetLink")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceUpdateLinkHandler := connect.NewUnaryHandler(
		RedirectServiceUpdateLinkProcedure,
		svc.UpdateLink,
		connect.WithSchema(redirectServiceMethods.ByName("UpdateLink")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceDeleteLinkHandler := connect.NewUnaryHandler(
		RedirectServiceDeleteLinkProcedure,
		svc.DeleteLink,
		connect.WithSchema(redirectServiceMethods.ByName("DeleteLink")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceListLinksHandler := connect.NewServerStreamHandler(
		RedirectServiceListLinksProcedure,
		svc.ListLinks,
		connect.WithSchema(redirectServiceMethods.ByName("ListLinks")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceGetLinkStatsHandler := connect.NewUnaryHandler(
		RedirectServiceGetLinkStatsProcedure,
		svc.GetLinkStats,
		connect.WithSchema(redirectServiceMethods.ByName("GetLinkStats")),
		connect.WithHandlerOptions(opts...),
	)
	redirectServiceListClicksHandler := connect.NewServerStreamHandler(
		RedirectServiceListClicksProcedure,
		svc.ListClicks,
		connect.WithSchema(redirectServiceMethods.ByName("ListClicks")),
		connect.WithHandlerOptions(opts...),
	)
	return "/redirect.v1.RedirectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RedirectServiceCreateLinkProcedure:
			redirectServiceCreateLinkHandler.ServeHTTP(w, r)
		case RedirectServiceGetLinkProcedure:
			redirectServiceGetLinkHandler.ServeHTTP(w, r)
		case RedirectServiceUpdateLinkProcedure:
			redirectServiceUpdateLinkHandler.ServeHTTP(w, r)
		case RedirectServiceDeleteLinkProcedure:
			redirectServiceDeleteLinkHandler.ServeHTTP(w, r)
		case RedirectServiceListLinksProcedure:
			redirectServiceListLinksHandler.ServeHTTP(w, r)
		case RedirectServiceGetLinkStatsProcedure:
			redirectServiceGetLinkStatsHandler.ServeHTTP(w, r)
		case RedirectServiceListClicksProcedure:
			redirectServiceListClicksHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRedirectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRedirectServiceHandler struct{}

func (UnimplementedRedirectServiceHandler) CreateLink(context.Context, *connect.Request[v1.CreateLinkRequest]) (*connect.Response[v1.CreateLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.CreateLink is not implemented"))
}

func (UnimplementedRedirectServiceHandler) GetLink(context.Context, *connect.Request[v1.GetLinkRequest]) (*connect.Response[v1.GetLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.GetLink is not implemented"))
}

func (UnimplementedRedirectServiceHandler) UpdateLink(context.Context, *connect.Request[v1.UpdateLinkRequest]) (*connect.Response[v1.UpdateLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.UpdateLink is not implemented"))
}

func (UnimplementedRedirectServiceHandler) DeleteLink(context.Context, *connect.Request[v1.DeleteLinkRequest]) (*connect.Response[v1.DeleteLinkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.DeleteLink is not implemented"))
}

func (UnimplementedRedirectServiceHandler) ListLinks(context.Context, *connect.Request[v1.ListLinksRequest], *connect.ServerStream[v1.ListLinksResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.ListLinks is not implemented"))
}

func (UnimplementedRedirectServiceHandler) GetLinkStats(context.Context, *connect.Request[v1.GetLinkStatsRequest]) (*connect.Response[v1.GetLinkStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.GetLinkStats is not implemented"))
}

func (UnimplementedRedirectServiceHandler) ListClicks(context.Context, *connect.Request[v1.ListClicksRequest], *connect.ServerStream[v1.ListClicksResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("redirect.v1.RedirectService.ListClicks is not implemented"))
}
