// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: redirect/v1/redirect.proto

package redirectpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LinkState represents the lifecycle state of a link.
type LinkState int32

const (
	LinkState_LINK_STATE_UNSPECIFIED LinkState = 0
	LinkState_LINK_STATE_ACTIVE      LinkState = 1
	LinkState_LINK_STATE_PAUSED      LinkState = 2
	LinkState_LINK_STATE_EXPIRED     LinkState = 3
	LinkState_LINK_STATE_DELETED     LinkState = 4
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "LINK_STATE_UNSPECIFIED",
		1: "LINK_STATE_ACTIVE",
		2: "LINK_STATE_PAUSED",
		3: "LINK_STATE_EXPIRED",
		4: "LINK_STATE_DELETED",
	}
	LinkState_value = map[string]int32{
		"LINK_STATE_UNSPECIFIED": 0,
		"LINK_STATE_ACTIVE":      1,
		"LINK_STATE_PAUSED":      2,
		"LINK_STATE_EXPIRED":     3,
		"LINK_STATE_DELETED":     4,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_redirect_v1_redirect_proto_enumTypes[0].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_redirect_v1_redirect_proto_enumTypes[0]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{0}
}

// DeviceType classifies the device that made the click.
type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_DESKTOP     DeviceType = 1
	DeviceType_DEVICE_TYPE_MOBILE      DeviceType = 2
	DeviceType_DEVICE_TYPE_TABLET      DeviceType = 3
	DeviceType_DEVICE_TYPE_BOT         DeviceType = 4
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_DESKTOP",
		2: "DEVICE_TYPE_MOBILE",
		3: "DEVICE_TYPE_TABLET",
		4: "DEVICE_TYPE_BOT",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_DESKTOP":     1,
		"DEVICE_TYPE_MOBILE":      2,
		"DEVICE_TYPE_TABLET":      3,
		"DEVICE_TYPE_BOT":         4,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_redirect_v1_redirect_proto_enumTypes[1].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_redirect_v1_redirect_proto_enumTypes[1]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{1}
}

// Link represents a redirect link with affiliate tracking metadata.
type Link struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Short slug used in the redirect URL (e.g., /r/{slug}).
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	// The destination URL to redirect to.
	DestinationUrl string `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	// Human-readable title for the link.
	Title string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	// ID of the affiliate who owns this link.
	AffiliateId string `protobuf:"bytes,5,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	// UTM-style campaign tracking fields.
	Campaign string `protobuf:"bytes,6,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Source   string `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Medium   string `protobuf:"bytes,8,opt,name=medium,proto3" json:"medium,omitempty"`
	Content  string `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
	Term     string `protobuf:"bytes,10,opt,name=term,proto3" json:"term,omitempty"`
	// Arbitrary tags for flexible categorisation.
	Tags *structpb.Struct `protobuf:"bytes,11,opt,name=tags,proto3" json:"tags,omitempty"`
	// Maximum number of clicks allowed (0 = unlimited).
	MaxClicks int64 `protobuf:"varint,12,opt,name=max_clicks,json=maxClicks,proto3" json:"max_clicks,omitempty"`
	// When the link expires (zero value = never).
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	State     LinkState              `protobuf:"varint,14,opt,name=state,proto3,enum=redirect.v1.LinkState" json:"state,omitempty"`
	// Denormalised total click count for fast reads.
	ClickCount int64 `protobuf:"varint,15,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	// Unique visitor count (deduplicated by IP within 24h window).
	UniqueClickCount int64                  `protobuf:"varint,16,opt,name=unique_click_count,json=uniqueClickCount,proto3" json:"unique_click_count,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt       *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Link) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

func (x *Link) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *Link) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Link) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *Link) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Link) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *Link) GetTags() *structpb.Struct {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Link) GetMaxClicks() int64 {
	if x != nil {
		return x.MaxClicks
	}
	return 0
}

func (x *Link) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Link) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *Link) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *Link) GetUniqueClickCount() int64 {
	if x != nil {
		return x.UniqueClickCount
	}
	return 0
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

// Click records a single redirect event with telemetry.
type Click struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LinkId         string                 `protobuf:"bytes,2,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	AffiliateId    string                 `protobuf:"bytes,3,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	IpAddress      string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent      string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referer        string                 `protobuf:"bytes,6,opt,name=referer,proto3" json:"referer,omitempty"`
	AcceptLanguage string                 `protobuf:"bytes,7,opt,name=accept_language,json=acceptLanguage,proto3" json:"accept_language,omitempty"`
	// Derived fields (parsed from user_agent / IP).
	Country    string     `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	City       string     `protobuf:"bytes,9,opt,name=city,proto3" json:"city,omitempty"`
	DeviceType DeviceType `protobuf:"varint,10,opt,name=device_type,json=deviceType,proto3,enum=redirect.v1.DeviceType" json:"device_type,omitempty"`
	Browser    string     `protobuf:"bytes,11,opt,name=browser,proto3" json:"browser,omitempty"`
	Os         string     `protobuf:"bytes,12,opt,name=os,proto3" json:"os,omitempty"`
	// The slug that was accessed.
	Slug          string                 `protobuf:"bytes,13,opt,name=slug,proto3" json:"slug,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Click) Reset() {
	*x = Click{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Click) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Click) ProtoMessage() {}

func (x *Click) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Click.ProtoReflect.Descriptor instead.
func (*Click) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{1}
}

func (x *Click) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Click) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *Click) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

func (x *Click) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Click) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Click) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *Click) GetAcceptLanguage() string {
	if x != nil {
		return x.AcceptLanguage
	}
	return ""
}

func (x *Click) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Click) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Click) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *Click) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *Click) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Click) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Click) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// LinkStats provides aggregate statistics for a link.
type LinkStats struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	LinkId       string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	TotalClicks  int64                  `protobuf:"varint,2,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks int64                  `protobuf:"varint,3,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	// Top referrers by click count.
	Referrers map[string]int64 `protobuf:"bytes,4,rep,name=referrers,proto3" json:"referrers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Clicks by country code.
	Countries map[string]int64 `protobuf:"bytes,5,rep,name=countries,proto3" json:"countries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Clicks by device type.
	Devices map[string]int64 `protobuf:"bytes,6,rep,name=devices,proto3" json:"devices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Clicks by browser name.
	Browsers map[string]int64 `protobuf:"bytes,7,rep,name=browsers,proto3" json:"browsers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Clicks by OS name.
	OperatingSystems map[string]int64 `protobuf:"bytes,8,rep,name=operating_systems,json=operatingSystems,proto3" json:"operating_systems,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Clicks per day (ISO date string -> count).
	ClicksPerDay  map[string]int64 `protobuf:"bytes,9,rep,name=clicks_per_day,json=clicksPerDay,proto3" json:"clicks_per_day,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStats) Reset() {
	*x = LinkStats{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStats) ProtoMessage() {}

func (x *LinkStats) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStats.ProtoReflect.Descriptor instead.
func (*LinkStats) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{2}
}

func (x *LinkStats) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *LinkStats) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *LinkStats) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *LinkStats) GetReferrers() map[string]int64 {
	if x != nil {
		return x.Referrers
	}
	return nil
}

func (x *LinkStats) GetCountries() map[string]int64 {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *LinkStats) GetDevices() map[string]int64 {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *LinkStats) GetBrowsers() map[string]int64 {
	if x != nil {
		return x.Browsers
	}
	return nil
}

func (x *LinkStats) GetOperatingSystems() map[string]int64 {
	if x != nil {
		return x.OperatingSystems
	}
	return nil
}

func (x *LinkStats) GetClicksPerDay() map[string]int64 {
	if x != nil {
		return x.ClicksPerDay
	}
	return nil
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Link                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLinkRequest) GetData() *Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Link                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLinkResponse) GetData() *Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{5}
}

func (x *GetLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Link                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{6}
}

func (x *GetLinkResponse) GetData() *Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationUrl string                 `protobuf:"bytes,2,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Campaign       string                 `protobuf:"bytes,4,opt,name=campaign,proto3" json:"campaign,omitempty"`
	Source         string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Medium         string                 `protobuf:"bytes,6,opt,name=medium,proto3" json:"medium,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Term           string                 `protobuf:"bytes,8,opt,name=term,proto3" json:"term,omitempty"`
	Tags           *structpb.Struct       `protobuf:"bytes,9,opt,name=tags,proto3" json:"tags,omitempty"`
	MaxClicks      int64                  `protobuf:"varint,10,opt,name=max_clicks,json=maxClicks,proto3" json:"max_clicks,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	State          LinkState              `protobuf:"varint,12,opt,name=state,proto3,enum=redirect.v1.LinkState" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLinkRequest) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *UpdateLinkRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateLinkRequest) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *UpdateLinkRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateLinkRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *UpdateLinkRequest) GetTags() *structpb.Struct {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateLinkRequest) GetMaxClicks() int64 {
	if x != nil {
		return x.MaxClicks
	}
	return 0
}

func (x *UpdateLinkRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *UpdateLinkRequest) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

type UpdateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Link                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLinkResponse) GetData() *Link {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AffiliateId   string                 `protobuf:"bytes,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	Campaign      string                 `protobuf:"bytes,3,opt,name=campaign,proto3" json:"campaign,omitempty"`
	State         LinkState              `protobuf:"varint,4,opt,name=state,proto3,enum=redirect.v1.LinkState" json:"state,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{11}
}

func (x *ListLinksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListLinksRequest) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

func (x *ListLinksRequest) GetCampaign() string {
	if x != nil {
		return x.Campaign
	}
	return ""
}

func (x *ListLinksRequest) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *ListLinksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLinksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Link                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{12}
}

func (x *ListLinksResponse) GetData() []*Link {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListLinksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetLinkStatsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	LinkId string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	// Optional date range for the stats window.
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkStatsRequest) Reset() {
	*x = GetLinkStatsRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkStatsRequest) ProtoMessage() {}

func (x *GetLinkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLinkStatsRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{13}
}

func (x *GetLinkStatsRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetLinkStatsRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *GetLinkStatsRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type GetLinkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LinkStats             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkStatsResponse) Reset() {
	*x = GetLinkStatsResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkStatsResponse) ProtoMessage() {}

func (x *GetLinkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkStatsResponse.ProtoReflect.Descriptor instead.
func (*GetLinkStatsResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{14}
}

func (x *GetLinkStatsResponse) GetData() *LinkStats {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListClicksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	AffiliateId   string                 `protobuf:"bytes,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClicksRequest) Reset() {
	*x = ListClicksRequest{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClicksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClicksRequest) ProtoMessage() {}

func (x *ListClicksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClicksRequest.ProtoReflect.Descriptor instead.
func (*ListClicksRequest) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{15}
}

func (x *ListClicksRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *ListClicksRequest) GetAffiliateId() string {
	if x != nil {
		return x.AffiliateId
	}
	return ""
}

func (x *ListClicksRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListClicksRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListClicksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClicksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListClicksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Click               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClicksResponse) Reset() {
	*x = ListClicksResponse{}
	mi := &file_redirect_v1_redirect_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClicksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClicksResponse) ProtoMessage() {}

func (x *ListClicksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirect_v1_redirect_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClicksResponse.ProtoReflect.Descriptor instead.
func (*ListClicksResponse) Descriptor() ([]byte, []int) {
	return file_redirect_v1_redirect_proto_rawDescGZIP(), []int{16}
}

func (x *ListClicksResponse) GetData() []*Click {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListClicksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_redirect_v1_redirect_proto protoreflect.FileDescriptor

const file_redirect_v1_redirect_proto_rawDesc = "" +
	"\n" +
	"\x1aredirect/v1/redirect.proto\x12\vredirect.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x95\x05\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\x04slug\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04slug\x121\n" +
	"\x0fdestination_url\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x0edestinationUrl\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12!\n" +
	"\faffiliate_id\x18\x05 \x01(\tR\vaffiliateId\x12\x1a\n" +
	"\bcampaign\x18\x06 \x01(\tR\bcampaign\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x16\n" +
	"\x06medium\x18\b \x01(\tR\x06medium\x12\x18\n" +
	"\acontent\x18\t \x01(\tR\acontent\x12\x12\n" +
	"\x04term\x18\n" +
	" \x01(\tR\x04term\x12+\n" +
	"\x04tags\x18\v \x01(\v2\x17.google.protobuf.StructR\x04tags\x12\x1d\n" +
	"\n" +
	"max_clicks\x18\f \x01(\x03R\tmaxClicks\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12,\n" +
	"\x05state\x18\x0e \x01(\x0e2\x16.redirect.v1.LinkStateR\x05state\x12\x1f\n" +
	"\vclick_count\x18\x0f \x01(\x03R\n" +
	"clickCount\x12,\n" +
	"\x12unique_click_count\x18\x10 \x01(\x03R\x10uniqueClickCount\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vmodified_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"\xb5\x03\n" +
	"\x05Click\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\alink_id\x18\x02 \x01(\tR\x06linkId\x12!\n" +
	"\faffiliate_id\x18\x03 \x01(\tR\vaffiliateId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x06 \x01(\tR\areferer\x12'\n" +
	"\x0faccept_language\x18\a \x01(\tR\x0eacceptLanguage\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\t \x01(\tR\x04city\x128\n" +
	"\vdevice_type\x18\n" +
	" \x01(\x0e2\x17.redirect.v1.DeviceTypeR\n" +
	"deviceType\x12\x18\n" +
	"\abrowser\x18\v \x01(\tR\abrowser\x12\x0e\n" +
	"\x02os\x18\f \x01(\tR\x02os\x12\x12\n" +
	"\x04slug\x18\r \x01(\tR\x04slug\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9d\a\n" +
	"\tLinkStats\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12!\n" +
	"\ftotal_clicks\x18\x02 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x03 \x01(\x03R\funiqueClicks\x12C\n" +
	"\treferrers\x18\x04 \x03(\v2%.redirect.v1.LinkStats.ReferrersEntryR\treferrers\x12C\n" +
	"\tcountries\x18\x05 \x03(\v2%.redirect.v1.LinkStats.CountriesEntryR\tcountries\x12=\n" +
	"\adevices\x18\x06 \x03(\v2#.redirect.v1.LinkStats.DevicesEntryR\adevices\x12@\n" +
	"\bbrowsers\x18\a \x03(\v2$.redirect.v1.LinkStats.BrowsersEntryR\bbrowsers\x12Y\n" +
	"\x11operating_systems\x18\b \x03(\v2,.redirect.v1.LinkStats.OperatingSystemsEntryR\x10operatingSystems\x12N\n" +
	"\x0eclicks_per_day\x18\t \x03(\v2(.redirect.v1.LinkStats.ClicksPerDayEntryR\fclicksPerDay\x1a<\n" +
	"\x0eReferrersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a<\n" +
	"\x0eCountriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a:\n" +
	"\fDevicesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a;\n" +
	"\rBrowsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aC\n" +
	"\x15OperatingSystemsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11ClicksPerDayEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\":\n" +
	"\x11CreateLinkRequest\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.redirect.v1.LinkR\x04data\";\n" +
	"\x12CreateLinkResponse\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.redirect.v1.LinkR\x04data\" \n" +
	"\x0eGetLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0fGetLinkResponse\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.redirect.v1.LinkR\x04data\"\x91\x03\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fdestination_url\x18\x02 \x01(\tR\x0edestinationUrl\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bcampaign\x18\x04 \x01(\tR\bcampaign\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06medium\x18\x06 \x01(\tR\x06medium\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12\x12\n" +
	"\x04term\x18\b \x01(\tR\x04term\x12+\n" +
	"\x04tags\x18\t \x01(\v2\x17.google.protobuf.StructR\x04tags\x12\x1d\n" +
	"\n" +
	"max_clicks\x18\n" +
	" \x01(\x03R\tmaxClicks\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12,\n" +
	"\x05state\x18\f \x01(\x0e2\x16.redirect.v1.LinkStateR\x05state\";\n" +
	"\x12UpdateLinkResponse\x12%\n" +
	"\x04data\x18\x01 \x01(\v2\x11.redirect.v1.LinkR\x04data\"#\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd1\x01\n" +
	"\x10ListLinksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\faffiliate_id\x18\x02 \x01(\tR\vaffiliateId\x12\x1a\n" +
	"\bcampaign\x18\x03 \x01(\tR\bcampaign\x12,\n" +
	"\x05state\x18\x04 \x01(\x0e2\x16.redirect.v1.LinkStateR\x05state\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"b\n" +
	"\x11ListLinksResponse\x12%\n" +
	"\x04data\x18\x01 \x03(\v2\x11.redirect.v1.LinkR\x04data\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xa0\x01\n" +
	"\x13GetLinkStatsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\"B\n" +
	"\x14GetLinkStatsResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.redirect.v1.LinkStatsR\x04data\"\xfd\x01\n" +
	"\x11ListClicksRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12!\n" +
	"\faffiliate_id\x18\x02 \x01(\tR\vaffiliateId\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"d\n" +
	"\x12ListClicksResponse\x12&\n" +
	"\x04data\x18\x01 \x03(\v2\x12.redirect.v1.ClickR\x04data\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*\x85\x01\n" +
	"\tLinkState\x12\x1a\n" +
	"\x16LINK_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LINK_STATE_ACTIVE\x10\x01\x12\x15\n" +
	"\x11LINK_STATE_PAUSED\x10\x02\x12\x16\n" +
	"\x12LINK_STATE_EXPIRED\x10\x03\x12\x16\n" +
	"\x12LINK_STATE_DELETED\x10\x04*\x87\x01\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DEVICE_TYPE_DESKTOP\x10\x01\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x02\x12\x16\n" +
	"\x12DEVICE_TYPE_TABLET\x10\x03\x12\x13\n" +
	"\x0fDEVICE_TYPE_BOT\x10\x042\xb8\x04\n" +
	"\x0fRedirectService\x12M\n" +
	"\n" +
	"CreateLink\x12\x1e.redirect.v1.CreateLinkRequest\x1a\x1f.redirect.v1.CreateLinkResponse\x12D\n" +
	"\aGetLink\x12\x1b.redirect.v1.GetLinkRequest\x1a\x1c.redirect.v1.GetLinkResponse\x12M\n" +
	"\n" +
	"UpdateLink\x12\x1e.redirect.v1.UpdateLinkRequest\x1a\x1f.redirect.v1.UpdateLinkResponse\x12M\n" +
	"\n" +
	"DeleteLink\x12\x1e.redirect.v1.DeleteLinkRequest\x1a\x1f.redirect.v1.DeleteLinkResponse\x12L\n" +
	"\tListLinks\x12\x1d.redirect.v1.ListLinksRequest\x1a\x1e.redirect.v1.ListLinksResponse0\x01\x12S\n" +
	"\fGetLinkStats\x12 .redirect.v1.GetLinkStatsRequest\x1a!.redirect.v1.GetLinkStatsResponse\x12O\n" +
	"\n" +
	"ListClicks\x12\x1e.redirect.v1.ListClicksRequest\x1a\x1f.redirect.v1.ListClicksResponse0\x01B\xbc\x01\n" +
	"\x0fcom.redirect.v1B\rRedirectProtoP\x01ZMstawi.jobs/pkg/services/redirectpb\xa2\x02\x03RXX\xaa\x02\vRedirect.V1\xca\x02\vRedirect\\V1\xe2\x02\x17Redirect\\V1\\GPBMetadata\xea\x02\fRedirect::V1b\x06proto3"

var (
	file_redirect_v1_redirect_proto_rawDescOnce sync.Once
	file_redirect_v1_redirect_proto_rawDescData []byte
)

func file_redirect_v1_redirect_proto_rawDescGZIP() []byte {
	file_redirect_v1_redirect_proto_rawDescOnce.Do(func() {
		file_redirect_v1_redirect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redirect_v1_redirect_proto_rawDesc), len(file_redirect_v1_redirect_proto_rawDesc)))
	})
	return file_redirect_v1_redirect_proto_rawDescData
}

var file_redirect_v1_redirect_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_redirect_v1_redirect_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_redirect_v1_redirect_proto_goTypes = []any{
	(LinkState)(0),                // 0: redirect.v1.LinkState
	(DeviceType)(0),               // 1: redirect.v1.DeviceType
	(*Link)(nil),                  // 2: redirect.v1.Link
	(*Click)(nil),                 // 3: redirect.v1.Click
	(*LinkStats)(nil),             // 4: redirect.v1.LinkStats
	(*CreateLinkRequest)(nil),     // 5: redirect.v1.CreateLinkRequest
	(*CreateLinkResponse)(nil),    // 6: redirect.v1.CreateLinkResponse
	(*GetLinkRequest)(nil),        // 7: redirect.v1.GetLinkRequest
	(*GetLinkResponse)(nil),       // 8: redirect.v1.GetLinkResponse
	(*UpdateLinkRequest)(nil),     // 9: redirect.v1.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),    // 10: redirect.v1.UpdateLinkResponse
	(*DeleteLinkRequest)(nil),     // 11: redirect.v1.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),    // 12: redirect.v1.DeleteLinkResponse
	(*ListLinksRequest)(nil),      // 13: redirect.v1.ListLinksRequest
	(*ListLinksResponse)(nil),     // 14: redirect.v1.ListLinksResponse
	(*GetLinkStatsRequest)(nil),   // 15: redirect.v1.GetLinkStatsRequest
	(*GetLinkStatsResponse)(nil),  // 16: redirect.v1.GetLinkStatsResponse
	(*ListClicksRequest)(nil),     // 17: redirect.v1.ListClicksRequest
	(*ListClicksResponse)(nil),    // 18: redirect.v1.ListClicksResponse
	nil,                           // 19: redirect.v1.LinkStats.ReferrersEntry
	nil,                           // 20: redirect.v1.LinkStats.CountriesEntry
	nil,                           // 21: redirect.v1.LinkStats.DevicesEntry
	nil,                           // 22: redirect.v1.LinkStats.BrowsersEntry
	nil,                           // 23: redirect.v1.LinkStats.OperatingSystemsEntry
	nil,                           // 24: redirect.v1.LinkStats.ClicksPerDayEntry
	(*structpb.Struct)(nil),       // 25: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 26: google.protobuf.Timestamp
}
var file_redirect_v1_redirect_proto_depIdxs = []int32{
	25, // 0: redirect.v1.Link.tags:type_name -> google.protobuf.Struct
	26, // 1: redirect.v1.Link.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 2: redirect.v1.Link.state:type_name -> redirect.v1.LinkState
	26, // 3: redirect.v1.Link.created_at:type_name -> google.protobuf.Timestamp
	26, // 4: redirect.v1.Link.modified_at:type_name -> google.protobuf.Timestamp
	1,  // 5: redirect.v1.Click.device_type:type_name -> redirect.v1.DeviceType
	26, // 6: redirect.v1.Click.created_at:type_name -> google.protobuf.Timestamp
	19, // 7: redirect.v1.LinkStats.referrers:type_name -> redirect.v1.LinkStats.ReferrersEntry
	20, // 8: redirect.v1.LinkStats.countries:type_name -> redirect.v1.LinkStats.CountriesEntry
	21, // 9: redirect.v1.LinkStats.devices:type_name -> redirect.v1.LinkStats.DevicesEntry
	22, // 10: redirect.v1.LinkStats.browsers:type_name -> redirect.v1.LinkStats.BrowsersEntry
	23, // 11: redirect.v1.LinkStats.operating_systems:type_name -> redirect.v1.LinkStats.OperatingSystemsEntry
	24, // 12: redirect.v1.LinkStats.clicks_per_day:type_name -> redirect.v1.LinkStats.ClicksPerDayEntry
	2,  // 13: redirect.v1.CreateLinkRequest.data:type_name -> redirect.v1.Link
	2,  // 14: redirect.v1.CreateLinkResponse.data:type_name -> redirect.v1.Link
	2,  // 15: redirect.v1.GetLinkResponse.data:type_name -> redirect.v1.Link
	25, // 16: redirect.v1.UpdateLinkRequest.tags:type_name -> google.protobuf.Struct
	26, // 17: redirect.v1.UpdateLinkRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 18: redirect.v1.UpdateLinkRequest.state:type_name -> redirect.v1.LinkState
	2,  // 19: redirect.v1.UpdateLinkResponse.data:type_name -> redirect.v1.Link
	0,  // 20: redirect.v1.ListLinksRequest.state:type_name -> redirect.v1.LinkState
	2,  // 21: redirect.v1.ListLinksResponse.data:type_name -> redirect.v1.Link
	26, // 22: redirect.v1.GetLinkStatsRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 23: redirect.v1.GetLinkStatsRequest.end_time:type_name -> google.protobuf.Timestamp
	4,  // 24: redirect.v1.GetLinkStatsResponse.data:type_name -> redirect.v1.LinkStats
	26, // 25: redirect.v1.ListClicksRequest.start_time:type_name -> google.protobuf.Timestamp
	26, // 26: redirect.v1.ListClicksRequest.end_time:type_name -> google.protobuf.Timestamp
	3,  // 27: redirect.v1.ListClicksResponse.data:type_name -> redirect.v1.Click
	5,  // 28: redirect.v1.RedirectService.CreateLink:input_type -> redirect.v1.CreateLinkRequest
	7,  // 29: redirect.v1.RedirectService.GetLink:input_type -> redirect.v1.GetLinkRequest
	9,  // 30: redirect.v1.RedirectService.UpdateLink:input_type -> redirect.v1.UpdateLinkRequest
	11, // 31: redirect.v1.RedirectService.DeleteLink:input_type -> redirect.v1.DeleteLinkRequest
	13, // 32: redirect.v1.RedirectService.ListLinks:input_type -> redirect.v1.ListLinksRequest
	15, // 33: redirect.v1.RedirectService.GetLinkStats:input_type -> redirect.v1.GetLinkStatsRequest
	17, // 34: redirect.v1.RedirectService.ListClicks:input_type -> redirect.v1.ListClicksRequest
	6,  // 35: redirect.v1.RedirectService.CreateLink:output_type -> redirect.v1.CreateLinkResponse
	8,  // 36: redirect.v1.RedirectService.GetLink:output_type -> redirect.v1.GetLinkResponse
	10, // 37: redirect.v1.RedirectService.UpdateLink:output_type -> redirect.v1.UpdateLinkResponse
	12, // 38: redirect.v1.RedirectService.DeleteLink:output_type -> redirect.v1.DeleteLinkResponse
	14, // 39: redirect.v1.RedirectService.ListLinks:output_type -> redirect.v1.ListLinksResponse
	16, // 40: redirect.v1.RedirectService.GetLinkStats:output_type -> redirect.v1.GetLinkStatsResponse
	18, // 41: redirect.v1.RedirectService.ListClicks:output_type -> redirect.v1.ListClicksResponse
	35, // [35:42] is the sub-list for method output_type
	28, // [28:35] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_redirect_v1_redirect_proto_init() }
func file_redirect_v1_redirect_proto_init() {
	if File_redirect_v1_redirect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redirect_v1_redirect_proto_rawDesc), len(file_redirect_v1_redirect_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redirect_v1_redirect_proto_goTypes,
		DependencyIndexes: file_redirect_v1_redirect_proto_depIdxs,
		EnumInfos:         file_redirect_v1_redirect_proto_enumTypes,
		MessageInfos:      file_redirect_v1_redirect_proto_msgTypes,
	}.Build()
	File_redirect_v1_redirect_proto = out.File
	file_redirect_v1_redirect_proto_goTypes = nil
	file_redirect_v1_redirect_proto_depIdxs = nil
}
