// Package cv implements the CV Strength Report pipeline: score the
// candidate's CV across five weighted dimensions, surface the fixes
// that would move the score the most, and generate before/after
// rewrite examples for the weakest experience bullets.
//
// The pipeline runs automatically after every CV upload/update and
// is callable on demand from the candidate dashboard. Every output
// is a structured CVStrengthReport — never free-form text — so the
// UI can render an interactive "apply fix → re-score" loop.
package cv

import "time"

// CVStrengthReport is the wire contract returned to the frontend.
// Every field is stable across model revisions; adding optional fields
// is safe, removing or renaming is not.
type CVStrengthReport struct {
	OverallScore  int             `json:"overall_score"` // 0-100 weighted rollup
	Components    ScoreComponents `json:"components"`
	TargetRole    string          `json:"target_role"`
	RoleFamily    string          `json:"role_family"` // programming/design/data/...
	PriorityFixes []PriorityFix   `json:"priority_fixes"`
	Rewrites      []BulletRewrite `json:"rewrites"`
	GeneratedAt   time.Time       `json:"generated_at"`
	CVVersion     string          `json:"cv_version"` // content hash, for cache + re-score detection
}

// ScoreComponents is the five per-dimension breakdown shown to the
// user. Each is 0-100; the overall score is the weighted average with
// the weights documented in scorer.go.
type ScoreComponents struct {
	ATS      int `json:"ats"`
	Keywords int `json:"keywords"`
	Impact   int `json:"impact"`
	RoleFit  int `json:"role_fit"`
	Clarity  int `json:"clarity"`
}

// PriorityFix is a single "do this first" action. The UI caps display
// at 7 to avoid paralysis — scorer.go's generator already honours the
// cap. AutoApplicable means the fix can be applied without user input
// (e.g. keyword additions, weak-verb substitutions); everything else
// needs confirmation.
type PriorityFix struct {
	ID             string   `json:"id"`       // stable identifier, e.g. "add-summary"
	Title          string   `json:"title"`    // human-readable heading
	Impact         string   `json:"impact"`   // high/medium/low
	Category       string   `json:"category"` // one of the five score components
	Why            string   `json:"why"`      // one-sentence justification
	AutoApplicable bool     `json:"auto_applicable"`
	Suggestions    []string `json:"suggestions,omitempty"` // e.g. list of keywords to add
}

// BulletRewrite is a concrete before/after pair for a single experience
// bullet. Generated by the LLM for the 5 weakest bullets.
type BulletRewrite struct {
	WorkIndex   int    `json:"work_index"`   // which WorkHistory entry
	BulletIndex int    `json:"bullet_index"` // which sentence within its summary
	Before      string `json:"before"`
	After       string `json:"after"`
	Reason      string `json:"reason"` // "added quantified impact", etc.
}
